root: true

env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

extends:
  - 'standard'

overrides:
  - files: ['*.ts']
    parser: '@typescript-eslint/parser'
    extends:
      - "plugin:@typescript-eslint/recommended"
    plugins: 
      - '@typescript-eslint'
    rules:
      '@typescript-eslint/no-explicit-any': 'off'

  - files: ['*.svelte']
    processor: 'svelte3/svelte3'
    plugins: 
      - 'svelte3'
    rules:
      import/first": 'off' 
      import/no-duplicates": 'off' 
      import/no-mutable-exports": 'off' 
      import/no-mutable-unresolved": 'off' 
      no-undef": 'off' 
      no-unused-vars": 'off'

rules:
  space-before-function-paren: 'off'
  no-multiple-empty-lines: 'off'
